<a href="https://colab.research.google.com/github/Sandeep354/Energyoutput-Regression/blob/main/Energy_Output_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Energy-pred.xlsx')

# Features Matrix
X = dataset.iloc[:, :-1].values #iloc[rows -> all needed, columns -> all except the last]

# Dependent Variable Vector (what we are going to predict)
y = dataset.iloc[:, -1].values #only last column needed

In [6]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [9]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
# We have to chose btw Sequential Layers and Computional Graph. We will do the first one
# Building a sequence of layers (we will make an object of sequential class)
# keras - sublibrary of tensorflow 2.0
ann = tf.keras.models.Sequential() 

### Adding the input layer and the first hidden layer

In [11]:
# units - no. of neurons in the 1st hidden layer (no need to specify units for input layer)
# (when we add the data, ann will automatically find the no.of input units)
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [12]:
# Same code for adding more layers (we can tweek the units and activation)
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [13]:
# if classification with binary - use sigmoid
# for more than 2 classification (categorical) - use softmax
# for regression - use defult None
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [14]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [15]:
ann.fit(x=X_train, y=y_train, epochs=100, batch_size=32)

Epoch 1/100
240/240 [==============================] - 0s 927us/step - loss: 223389.2031
Epoch 2/100
240/240 [==============================] - 0s 812us/step - loss: 2696.7463
Epoch 3/100
240/240 [==============================] - 0s 836us/step - loss: 336.6451
Epoch 4/100
240/240 [==============================] - 0s 804us/step - loss: 332.5417
Epoch 5/100
240/240 [==============================] - 0s 868us/step - loss: 327.6067
Epoch 6/100
240/240 [==============================] - 0s 832us/step - loss: 321.9160
Epoch 7/100
240/240 [==============================] - 0s 824us/step - loss: 315.2934
Epoch 8/100
240/240 [==============================] - 0s 799us/step - loss: 308.1312
Epoch 9/100
240/240 [==============================] - 0s 811us/step - loss: 299.9357
Epoch 10/100
240/240 [==============================] - 0s 840us/step - loss: 291.2037
Epoch 11/100
240/240 [==============================] - 0s 907us/step - loss: 281.3427
Epoch 12/100
240/240 [==========================

### Predicting the results of the Test set

In [17]:
y_pred = ann.predict(x=X_test)

# setting only 2 decimal places
np.set_printoptions(precision=2)

# Put the predictions and true value matrix vertically and compare (vertical concatenate - axis=1)
comparison = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), axis=1)

print (comparison)



[[432.45 431.23]
 [463.5  460.01]
 [467.   461.14]
 ...
 [474.25 473.26]
 [440.98 438.  ]
 [460.22 463.28]]
